build_test:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    script:
        - dotnet restore TweetTxoutSet.sln
        - dotnet build TweetTxoutSet.sln
    only:
        - master

docker_publisher:
    image: docker:stable
    variables:
        CONTAINER_IMAGE: registry.gitlab.com/r0ckstardev/tweettxoutset/publisher:$CI_COMMIT_REF_NAME
        DOCKER_HOST: tcp://docker:2375
        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - docker build -t $CONTAINER_IMAGE -f TxoutSet.Publisher/Dockerfile .
        - docker push $CONTAINER_IMAGE
    only:
        - tags